import type { DialogueNode } from "../../lesson.types";

export const airportArrivalDialogue = [
  {
    id: "welcome",
    lineIds: ["welcome-neutral", "welcome-warm"],
    hint: "Você pode responder com “preciso de ajuda”.",
    exampleAnswers: ["Sim, preciso de ajuda.", "Pode me ajudar?"],
    acceptedIntents: [
      "need_help",
      "no_help",
      "baggage_problem",
      "baggage_not_collected",
      "greeting",
    ],
    transitions: {
      need_help: "baggage-status",
      no_help: "closing",
      baggage_problem: "baggage-area",
      baggage_not_collected: "baggage-area",
      greeting: "welcome",
    },
    fallbackNodeId: "welcome",
    powerReward: 8,
  },
  {
    id: "baggage-status",
    lineIds: ["baggage-status-neutral", "baggage-status-warm"],
    hint: "Para dizer que ainda não, use “ainda não”.",
    exampleAnswers: ["Ainda não.", "Não, ainda não."],
    acceptedIntents: [
      "already_have_baggage",
      "baggage_not_collected",
      "baggage_problem",
    ],
    transitions: {
      already_have_baggage: "ask-location",
      baggage_not_collected: "baggage-area",
      baggage_problem: "baggage-area",
    },
    fallbackNodeId: "baggage-status",
    powerReward: 8,
  },
  {
    id: "baggage-area",
    lineIds: ["baggage-area-neutral", "baggage-area-brief"],
    hint: "Confirme com “sim” ou diga que procura a bagagem.",
    exampleAnswers: ["Sim.", "Estou procurando a bagagem."],
    acceptedIntents: ["confirm_baggage_area", "deny", "ask_location"],
    transitions: {
      confirm_baggage_area: "ask-location",
      deny: "baggage-status",
      ask_location: "direction",
    },
    fallbackNodeId: "baggage-area",
    powerReward: 8,
  },
  {
    id: "ask-location",
    lineIds: ["ask-location-neutral", "ask-location-warm"],
    hint: "Pergunte usando “onde fica?”.",
    exampleAnswers: ["Onde fica?", "Não. Onde fica?"],
    acceptedIntents: ["ask_location", "know_location"],
    transitions: {
      ask_location: "direction",
      know_location: "direction-confirmation",
    },
    fallbackNodeId: "ask-location",
    powerReward: 8,
  },
  {
    id: "direction",
    lineIds: ["direction-neutral", "direction-detailed"],
    hint: "A direção principal é “à direita”.",
    exampleAnswers: ["Entendi.", "À direita?"],
    acceptedIntents: ["understood"],
    transitions: {
      understood: "direction-confirmation",
    },
    fallbackNodeId: "direction",
    powerReward: 8,
  },
  {
    id: "direction-confirmation",
    lineIds: ["direction-confirmation-neutral", "direction-confirmation-warm"],
    hint: "Você pode agradecer ou confirmar que entendeu.",
    exampleAnswers: ["Obrigado.", "Obrigado pela ajuda."],
    acceptedIntents: ["thanks", "understood"],
    transitions: {
      thanks: "closing",
      understood: "closing",
    },
    fallbackNodeId: "direction-confirmation",
    powerReward: 8,
  },
  {
    id: "closing",
    lineIds: ["closing-neutral", "closing-warm"],
    acceptedIntents: [],
    transitions: {},
    terminal: true,
  },
] as const satisfies readonly DialogueNode[];
