import type { DialogueNode } from "../../lesson.types";

export const airportArrivalDialogue = [
  {
    id: "welcome",
    speaker: "Funcionária do aeroporto",
    text: "Oi! Bem-vindo ao Brasil. Você precisa de ajuda?",
    translation: "¡Hola! Bienvenido a Brasil. ¿Necesitás ayuda?",
    slowText: "Oi! · Bem-vindo ao Brasil. · Você precisa de ajuda?",
    hint: "Você pode responder com “preciso de ajuda”.",
    exampleAnswers: ["Sim, preciso de ajuda.", "Pode me ajudar?"],
    acceptedIntents: ["need_help", "no_help", "dont_understand", "ask_repeat"],
    transitions: {
      need_help: "baggage-status",
      no_help: "closing",
      dont_understand: "welcome",
      ask_repeat: "welcome",
    },
    fallbackNodeId: "welcome",
    powerReward: 8,
    expression: "neutral",
  },
  {
    id: "baggage-status",
    speaker: "Funcionária do aeroporto",
    text: "Claro. Você já pegou sua bagagem?",
    translation: "Claro. ¿Ya retiraste tu equipaje?",
    slowText: "Claro. · Você já pegou · sua bagagem?",
    hint: "Para dizer que ainda não, use “ainda não”.",
    exampleAnswers: ["Ainda não.", "Não, ainda não."],
    acceptedIntents: ["already_have_baggage", "not_yet", "dont_understand"],
    transitions: {
      already_have_baggage: "ask-location",
      not_yet: "baggage-area",
      dont_understand: "baggage-status",
    },
    fallbackNodeId: "baggage-status",
    powerReward: 8,
  },
  {
    id: "baggage-area",
    speaker: "Funcionária do aeroporto",
    text: "Você está procurando a retirada de bagagem?",
    translation: "¿Estás buscando el retiro de equipaje?",
    slowText: "Você está procurando · a retirada de bagagem?",
    hint: "Confirme com “sim” ou diga que procura a bagagem.",
    exampleAnswers: ["Sim.", "Estou procurando a bagagem."],
    acceptedIntents: ["confirm_baggage_area", "deny", "dont_understand"],
    transitions: {
      confirm_baggage_area: "ask-location",
      deny: "baggage-status",
      dont_understand: "baggage-area",
    },
    fallbackNodeId: "baggage-area",
    powerReward: 8,
  },
  {
    id: "ask-location",
    speaker: "Funcionária do aeroporto",
    text: "Posso te mostrar. Você sabe onde fica?",
    translation: "Puedo mostrarte. ¿Sabés dónde queda?",
    slowText: "Posso te mostrar. · Você sabe · onde fica?",
    hint: "Pergunte usando “onde fica?”.",
    exampleAnswers: ["Onde fica?", "Não. Onde fica?"],
    acceptedIntents: ["ask_location", "know_location", "dont_understand"],
    transitions: {
      ask_location: "direction",
      know_location: "direction-confirmation",
      dont_understand: "ask-location",
    },
    fallbackNodeId: "ask-location",
    powerReward: 8,
  },
  {
    id: "direction",
    speaker: "Funcionária do aeroporto",
    text: "Fica logo à direita, depois daquele painel.",
    translation: "Queda enseguida a la derecha, después de aquel panel.",
    slowText: "Fica logo à direita · depois daquele painel.",
    hint: "A direção principal é “à direita”.",
    exampleAnswers: ["Entendi.", "À direita?"],
    acceptedIntents: ["understood_direction", "ask_repeat", "dont_understand"],
    transitions: {
      understood_direction: "direction-confirmation",
      ask_repeat: "direction",
      dont_understand: "direction",
    },
    fallbackNodeId: "direction",
    powerReward: 8,
  },
  {
    id: "direction-confirmation",
    speaker: "Funcionária do aeroporto",
    text: "Isso. Siga em frente e vire à direita.",
    translation: "Eso. Seguí derecho y doblá a la derecha.",
    slowText: "Isso. · Siga em frente · e vire à direita.",
    hint: "Você pode agradecer ou confirmar que entendeu.",
    exampleAnswers: ["Obrigado.", "Obrigado pela ajuda."],
    acceptedIntents: ["thanks", "acknowledge", "dont_understand"],
    transitions: {
      thanks: "closing",
      acknowledge: "closing",
      dont_understand: "direction-confirmation",
    },
    fallbackNodeId: "direction-confirmation",
    powerReward: 8,
  },
  {
    id: "closing",
    speaker: "Funcionária do aeroporto",
    text: "De nada! Boa viagem e aproveite o Brasil.",
    translation: "¡De nada! Buen viaje y disfrutá Brasil.",
    slowText: "De nada! · Boa viagem · e aproveite o Brasil.",
    acceptedIntents: [],
    transitions: {},
    expression: "smile",
    terminal: true,
  },
] as const satisfies readonly DialogueNode[];
