import type { NpcLine, RecoveryKind } from "../../lesson.types";

const agent = "Funcionária do aeroporto";

export const airportArrivalLines = [
  {
    id: "welcome-neutral",
    speaker: agent,
    text: "Oi! Bem-vindo ao Brasil. Você precisa de ajuda?",
    translation: "¡Hola! Bienvenido a Brasil. ¿Necesitás ayuda?",
    slowText: "Oi! · Bem-vindo ao Brasil. · Você precisa de ajuda?",
    expression: "neutral",
    emotion: "warm",
  },
  {
    id: "welcome-warm",
    speaker: agent,
    text: "Olá! Seja bem-vindo. Posso ajudar você com a sua chegada?",
    translation: "¡Hola! Bienvenido. ¿Puedo ayudarte con tu llegada?",
    slowText: "Olá! · Seja bem-vindo. · Posso ajudar você · com a sua chegada?",
    expression: "smile",
    emotion: "warm",
  },
  {
    id: "baggage-status-neutral",
    speaker: agent,
    text: "Claro. Você já pegou sua bagagem?",
    translation: "Claro. ¿Ya retiraste tu equipaje?",
    slowText: "Claro. · Você já pegou · sua bagagem?",
    emotion: "focused",
  },
  {
    id: "baggage-status-warm",
    speaker: agent,
    text: "Com certeza, eu ajudo. Sua bagagem já está com você?",
    translation: "Por supuesto, te ayudo. ¿Ya tenés tu equipaje?",
    slowText: "Com certeza, · eu ajudo. · Sua bagagem · já está com você?",
    emotion: "reassuring",
  },
  {
    id: "baggage-area-neutral",
    speaker: agent,
    text: "Você está procurando a retirada de bagagem?",
    translation: "¿Estás buscando el retiro de equipaje?",
    slowText: "Você está procurando · a retirada de bagagem?",
    emotion: "focused",
  },
  {
    id: "baggage-area-brief",
    speaker: agent,
    text: "Entendi. Você precisa chegar à retirada de bagagem, certo?",
    translation: "Entiendo. Necesitás llegar al retiro de equipaje, ¿verdad?",
    slowText: "Entendi. · Você precisa chegar · à retirada de bagagem, · certo?",
    emotion: "reassuring",
  },
  {
    id: "ask-location-neutral",
    speaker: agent,
    text: "Posso te mostrar. Você sabe onde fica?",
    translation: "Puedo mostrarte. ¿Sabés dónde queda?",
    slowText: "Posso te mostrar. · Você sabe · onde fica?",
    emotion: "warm",
  },
  {
    id: "ask-location-warm",
    speaker: agent,
    text: "Sem problema. Você quer que eu explique onde fica?",
    translation: "No hay problema. ¿Querés que te explique dónde queda?",
    slowText: "Sem problema. · Você quer que eu explique · onde fica?",
    emotion: "reassuring",
  },
  {
    id: "direction-neutral",
    speaker: agent,
    text: "Fica logo à direita, depois daquele painel.",
    translation: "Queda enseguida a la derecha, después de aquel panel.",
    slowText: "Fica logo à direita · depois daquele painel.",
    expression: "neutral",
    emotion: "focused",
  },
  {
    id: "direction-detailed",
    speaker: agent,
    text: "Siga em frente até o painel e vire à direita. É bem perto.",
    translation: "Seguí derecho hasta el panel y doblá a la derecha. Está muy cerca.",
    slowText: "Siga em frente · até o painel · e vire à direita. · É bem perto.",
    emotion: "reassuring",
  },
  {
    id: "direction-confirmation-neutral",
    speaker: agent,
    text: "Isso. Siga em frente e vire à direita.",
    translation: "Eso. Seguí derecho y doblá a la derecha.",
    slowText: "Isso. · Siga em frente · e vire à direita.",
    emotion: "focused",
  },
  {
    id: "direction-confirmation-warm",
    speaker: agent,
    text: "Perfeito. É só seguir em frente e virar à direita.",
    translation: "Perfecto. Sólo tenés que seguir derecho y doblar a la derecha.",
    slowText: "Perfeito. · É só seguir em frente · e virar à direita.",
    expression: "smile",
    emotion: "warm",
  },
  {
    id: "closing-neutral",
    speaker: agent,
    text: "De nada! Boa viagem e aproveite o Brasil.",
    translation: "¡De nada! Buen viaje y disfrutá Brasil.",
    slowText: "De nada! · Boa viagem · e aproveite o Brasil.",
    expression: "smile",
    emotion: "warm",
  },
  {
    id: "closing-warm",
    speaker: agent,
    text: "Foi um prazer ajudar. Boa viagem e seja bem-vindo ao Brasil!",
    translation: "Fue un placer ayudarte. ¡Buen viaje y bienvenido a Brasil!",
    slowText: "Foi um prazer ajudar. · Boa viagem · e seja bem-vindo ao Brasil!",
    expression: "smile",
    emotion: "warm",
  },
  {
    id: "recovery-unclear-1",
    speaker: agent,
    text: "Não entendi bem. Pode dizer de outro jeito?",
    slowText: "Não entendi bem. · Pode dizer · de outro jeito?",
    expression: "confused",
    emotion: "reassuring",
  },
  {
    id: "recovery-unclear-2",
    speaker: agent,
    text: "Tudo bem, vamos tentar de novo. O que você precisa?",
    slowText: "Tudo bem, · vamos tentar de novo. · O que você precisa?",
    expression: "neutral",
    emotion: "reassuring",
  },
  {
    id: "recovery-partial-1",
    speaker: agent,
    text: "Acho que entendi uma parte. Pode completar para mim?",
    slowText: "Acho que entendi · uma parte. · Pode completar · para mim?",
    expression: "neutral",
    emotion: "reassuring",
  },
  {
    id: "recovery-partial-2",
    speaker: agent,
    text: "Estamos quase lá. Diga um pouco mais para eu ajudar.",
    slowText: "Estamos quase lá. · Diga um pouco mais · para eu ajudar.",
    expression: "smile",
    emotion: "warm",
  },
  {
    id: "recovery-ambiguous-1",
    speaker: agent,
    text: "Só para confirmar: qual das opções você quer dizer?",
    slowText: "Só para confirmar: · qual das opções · você quer dizer?",
    expression: "neutral",
    emotion: "focused",
  },
  {
    id: "recovery-ambiguous-2",
    speaker: agent,
    text: "Entendi duas possibilidades. Pode escolher uma delas para mim?",
    slowText: "Entendi duas possibilidades. · Pode escolher uma delas · para mim?",
    expression: "neutral",
    emotion: "reassuring",
  },
  {
    id: "recovery-off-topic-1",
    speaker: agent,
    text: "Entendo. Primeiro vamos cuidar da sua chegada ao aeroporto. Como posso ajudar?",
    slowText: "Entendo. · Primeiro vamos cuidar · da sua chegada ao aeroporto. · Como posso ajudar?",
    expression: "neutral",
    emotion: "warm",
  },
  {
    id: "recovery-off-topic-2",
    speaker: agent,
    text: "Podemos falar disso depois. Agora, vamos resolver o que você precisa no aeroporto.",
    slowText: "Podemos falar disso depois. · Agora, vamos resolver · o que você precisa · no aeroporto.",
    expression: "smile",
    emotion: "reassuring",
  },
  {
    id: "recovery-silence-1",
    speaker: agent,
    text: "Não ouvi sua resposta. Sem problema, pode tentar novamente.",
    slowText: "Não ouvi sua resposta. · Sem problema, · pode tentar novamente.",
    expression: "neutral",
    emotion: "reassuring",
  },
  {
    id: "recovery-silence-2",
    speaker: agent,
    text: "Parece que o áudio ficou baixo. Você pode falar de novo ou escrever.",
    slowText: "Parece que o áudio · ficou baixo. · Você pode falar de novo · ou escrever.",
    expression: "neutral",
    emotion: "reassuring",
  },
] as const satisfies readonly NpcLine[];

export const airportRecoveryLineIds = {
  unclear: ["recovery-unclear-1", "recovery-unclear-2"],
  partial_match: ["recovery-partial-1", "recovery-partial-2"],
  ambiguous: ["recovery-ambiguous-1", "recovery-ambiguous-2"],
  off_topic: ["recovery-off-topic-1", "recovery-off-topic-2"],
  silence: ["recovery-silence-1", "recovery-silence-2"],
} as const satisfies Readonly<Record<RecoveryKind, readonly string[]>>;
